#!/usr/bin/env ruby

require 'mixlib/shellout'
require 'cinch'

# Wrapper for the build_and_publish rake task
# Assumes you have permission to packages.flapjack.io S3 bucket for writing

distro, distro_release, build_ref = ARGV
tstamp = Time.now.utc.strftime('%Y%m%dT%H%M%S')

unless distro && distro_release && build_ref
  puts "Must be called with the following arguments:"
  puts "  build_and_publish DISTRO DISTRO_RELEASE BUILD_REF"
  puts "eg:"
  puts "  build_and_publish ubuntu precise v1.2.0rc2"
  exit 1
end

log = "flapjack_#{build_ref}-#{tstamp}-#{distro}-#{distro_release}.log"

Mixlib::ShellOut.new("echo 'Running build of #{build_ref} on #{distro} " +
  "#{distro_release} at #{tstamp}' | tee -a #{log}").run_command.error!

Mixlib::ShellOut.new("BUILD_REF=#{build_ref} DISTRO=#{distro} " +
  "DISTRO_RELEASE=#{distro_release} time bundle exec rake build_and_publish 2>&1 | tee #{log}").run_command.error!

Mixlib::ShellOut.new("echo 'FINISHED #{build_ref} on #{distro} " +
  "#{distro_release} AT `date` (uptime: `uptime`)' | tee #{log}").run_command.error!

log_dst = "packages.flapjack.io/build_logs/#{log}"
puts "Done. Uploading log to #{log_dst}"
Mixlib::ShellOut.new("aws s3 cp #{log} s3://#{log_dst}").run_command.error!

message = "Completed building and publishing of experimental Flapjack package: #{build_ref} for #{distro} #{distro_release}, build log: http://#{log_dst}"

puts 'sending message to #flapjack: ' + message
bot = Cinch::Bot.new do
  configure do |c|
    c.server = "irc.freenode.org"
    c.channels = ["#flapjack"]
  end

  on :connect do |connection|
    Channel('#flapjack').send(message)
    bot.quit
  end
end

bot.start
