#!/usr/bin/env ruby

s3_url = ARGV[0] || 's3://flapjack-packages/new/'

def run(command)
  #puts "running command: " + command
  unless system(command)
    puts "Error running the following command:"
    puts "  #{command}"
    exit 1
  end
end

deb = `ls ~/omnibus-flapjack/pkg/flapjack*deb | tail -1`.chomp
metadata = deb + ".metadata.json"

raise "no deb found at #{deb.inspect}" unless File.file?(deb)
raise "no metadata found for #{deb}" unless File.file?(metadata)

puts "Storing #{deb} into #{s3_url}"
run("aws s3 cp #{deb} #{s3_url}")
puts "Storing #{metadata} into #{s3_url}"
run("aws s3 cp #{metadata} #{s3_url}")

