#!/bin/bash

echo 'deb http://repo.aptly.info/ squeeze main' > /etc/apt/sources.list.d/aptly.list
gpg --keyserver keys.gnupg.net --recv-keys 2A194991
gpg -a --export 2A194991 | apt-key add -

apt-get update
apt-get install -y aptly

retval=$?
if [ "${retval}" -ne "0" ] ; then echo "Error installing aptly. retval: $retval" ; exit $retval ; fi

aptly -config=/omnibus-flapjack/hacks/aptly.conf repo show flapjack
retval=$?
if [ "${retval}" -ne "0" ] ; then
  echo "Flapjack repository already exists."
  aptly -config=/omnibus-flapjack/hacks/aptly.conf -distribution 'experimental' repo create flapjack
  retval=$?
  if [ "${retval}" -ne "0" ] ; then
    echo "Error creating flapjack repository. retval: $retval"; exit $retval
  fi
fi

for i in `find /omnibus-flapjack/pkg/ -name *.deb`; do aptly repo add flapjack ${i}; done
retval=$?
if [ "${retval}" -ne "0" ] ; then echo "Error adding deb to repostory. retval: $retval" ; exit $retval ; fi

aptly -config=/omnibus-flapjack/hacks/aptly.conf repo show flapjack

aptly -config=/omnibus-flapjack/hacks/aptly.conf publish repo flapjack s3:test:deb
retval=$?
if [ "${retval}" -ne "0" ] ; then echo "Error publishing to S3. retval: $retval" ; exit $retval ; fi
