#!/bin/bash
#
# Perform necessary flapjack removal steps
# after package is uninstalled.
#

if [ -f /etc/redhat-release ]; then
  INITDDIR="/etc/rc.d/init.d"
else
  INITDDIR="/etc/init.d"
fi

if [ -e ${FLAPJACK_GEM_DIR}/etc/flapjack_config.yaml.example ]; then
  FLAPJACK_CONFIG_VERSION="1"
elif [ -e ${FLAPJACK_GEM_DIR}/etc/flapjack_config.toml.example ]; then
  FLAPJACK_CONFIG_VERSION="2"
fi

if [ -f /etc/redhat-release ]; then
  chkconfig --del redis-flapjack
  chkconfig --del flapjack
  if [ "${FLAPJACK_CONFIG_VERSION}" == "1" ]; then
    chkconfig --del flapjack-nagios-receiver
  fi
  chkconfig --del flapper
else
  update-rc.d flapjack remove
  if [ "${FLAPJACK_CONFIG_VERSION}" == "1" ]; then
    update-rc.d flapjack-nagios-receiver remove
  fi
  update-rc.d flapper remove
  update-rc.d redis-flapjack remove
fi

echo "flapjack has been uninstalled!"

exit 0
