#!/bin/bash
#
# Perform necessary flapjack setup steps
# after package is installed.
#

INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/flapjack
CONFIG_DIR=/etc/flapjack
FLAPJACK_GEM_DIR=`ls -dr ${DEST_DIR}/embedded/lib/ruby/gems/*/gems/flapjack-* | head -1`
PROGNAME=$(basename $0)

adduser --system --quiet --group --no-create-home flapjack

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Set up config + logging directories
mkdir -p /etc/flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack/redis-flapjack
chown -R flapjack:flapjack /var/log/flapjack /var/run/flapjack /var/lib/flapjack

# Copy in default configuration if none exists already
if [ ! -e /etc/flapjack/flapjack_config.yaml ] ; then
  echo "Creating /etc/flapjack/flapjack_config.yaml"
  cp ${FLAPJACK_GEM_DIR}/etc/flapjack_config.yaml.example ${CONFIG_DIR}/flapjack_config.yaml
fi

# Copy in init scripts (FIXME: support OS's other than Ubunbu)

if [ ! -e /etc/init.d/redis-flapjack ] ; then
  echo "Creating /etc/init.d/redis-flapjack"
  cp ${DEST_DIR}/embedded/etc/init.d/redis-flapjack /etc/init.d/redis-flapjack
  chmod u+x /etc/init.d/redis-flapjack
fi

if [ ! -e /etc/init.d/flapjack ] ; then
  echo "Creating /etc/init.d/flapjack"
  cp ${FLAPJACK_GEM_DIR}/dist/etc/init.d/flapjack /etc/init.d/flapjack
  chmod u+x /etc/init.d/flapjack
fi

if [ ! -e /etc/init.d/flapjack-nagios-receiver ] ; then
  echo "Creating /etc/init.d/flapjack-nagios-receiver"
  cp ${FLAPJACK_GEM_DIR}/dist/etc/init.d/flapjack-nagios-receiver /etc/init.d/flapjack-nagios-receiver
  chmod u+x /etc/init.d/flapjack-nagios-receiver
fi

if [ ! -e /etc/init.d/flapper ] ; then
  echo "Creating /etc/init.d/flapper"
  cp ${FLAPJACK_GEM_DIR}/dist/etc/init.d/flapper /etc/init.d/flapper
  chmod u+x /etc/init.d/flapper
fi

update-rc.d redis-flapjack defaults 94 06 >/dev/null || exit $?
update-rc.d flapjack defaults 95 05 >/dev/null || exit $?

echo "Setting paths"
if [ ! -e /etc/profile.d/flapjack.sh ] ; then
  cat > /etc/profile.d/flapjack.sh <<'EOF'
PATH=$PATH:/opt/flapjack/bin
EOF
  chmod 644 /etc/profile.d/flapjack.sh
fi

echo "Starting redis-flapjack"
/etc/init.d/redis-flapjack start || exit $?

echo "Starting flapjack"
/etc/init.d/flapjack start || exit $?

echo "Thank you for installing flapjack!"
echo "Flapjack should now be running. Visit http://localhost:3080/"

exit 0

