#!/bin/bash
#
# Perform necessary flapjack removal steps
# after package is uninstalled.
#

if [ -f /etc/redhat-release ]; then
  INITDDIR="/etc/rc.d/init.d"
else
  INITDDIR="/etc/init.d"
fi

if [ -f /etc/redhat-release ]; then
  chkconfig --del redis-flapjack
  chkconfig --del flapjack
  chkconfig --del flapjack-nagios-receiver
  chkconfig --del flapper
else
  update-rc.d flapjack remove
  update-rc.d flapjack-nagios-receiver remove
  update-rc.d flapper remove
  update-rc.d redis-flapjack remove
fi

echo "flapjack has been uninstalled!"

exit 0
