#!/bin/bash
#
# Perform necessary flapjack removal steps
# after package is uninstalled.
#
if [ -f /etc/redhat-release ]; then 
    # Better to exit than the break the full postuninstall 
    exit 0
fi

rm /etc/init.d/flapjack /etc/init.d/flapjack-nagios-receiver /etc/init.d/flapper /etc/init.d/redis-flapjack
update-rc.d flapjack remove
update-rc.d flapjack-nagios-receiver remove
update-rc.d flapper remove
update-rc.d redis-flapjack remove

echo "flapjack has been uninstalled!"

exit 0
